### ISSUE TITLE
Samtools index: invalid option -- '@'/ AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by ayixon** [huangnengCSU/NeuralPolish#1]
Hello developer, I am having these errors when running neuralpolish. Any clue what I'm missing?
Thank you very much for the tool
...
---------- Samtools ------------

index: invalid option -- '@'
Usage: samtools index [-bc] [-m INT] <in.bam> [out.index]
Options:
  -b       Generate BAI-format index for BAM files [default]
  -c       Generate CSI-format index for BAM files
  -m INT   Set minimum interval size for CSI indices to 2^INT [14]

---------- Generating features ------------

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/neuralpolish/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/user/miniconda3/envs/neuralpolish/lib/python3.9/multiprocessing/pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/mnt/d/user1/Unicy_Cons_Fitlong_hard04/NeuralPolish/neuralpolishextract/run_samtools.py", line 53, in run_samtools_and_parse_alignment
    returnCode = subprocess.run(samtools_command, shell=True, check=True)
  File "/home/user/miniconda3/envs/neuralpolish/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'samtools mpileup -B --reference /mnt/d/user1/Unicy_Cons_Fitlong_hard04/NeuralPolish/test04/assembly_racon.fasta -r 1:660001-670000 --output-QNAME /mnt/d/user1/Unicy_Cons_Fitlong_hard04/NeuralPolish/test04/filter_aln.sort.bam -q 0 -Q 13 -o /mnt/d/user1/Unicy_Cons_Fitlong_hard04/NeuralPolish/test04/pileups/1:660001-670000.mpileup >> log.txt 2>&1' returned non-zero exit status 1.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/d/user1/Unicy_Cons_Fitlong_hard04/NeuralPolish/neuralpolishextract/run_samtools.py", line 116, in <module>
    threads_generate_inference_features(
  File "/mnt/d/user1/Unicy_Cons_Fitlong_hard04/NeuralPolish/neuralpolishextract/run_samtools.py", line 80, in threads_generate_inference_features
    pool.starmap(run_samtools_and_parse_alignment, thread_params)
  File "/home/user/miniconda3/envs/neuralpolish/lib/python3.9/multiprocessing/pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/home/user/miniconda3/envs/neuralpolish/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
subprocess.CalledProcessError: Command 'samtools mpileup -B --reference /mnt/d/user1/Unicy_Cons_Fitlong_hard04/NeuralPolish/test04/assembly_racon.fasta -r 1:660001-670000 --output-QNAME /mnt/d/user1/Unicy_Cons_Fitlong_hard04/NeuralPolish/test04/filter_aln.sort.bam -q 0 -Q 13 -o /mnt/d/user1/Unicy_Cons_Fitlong_hard04/NeuralPolish/test04/pileups/1:660001-670000.mpileup >> log.txt 2>&1' returned non-zero exit status 1.

---------- Network polishing ------------

/mnt/d/user1/Unicy_Cons_Fitlong_hard04/NeuralPolish/brnn/ctc_polish.py:26: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = AttrDict(yaml.load(configfile))
Traceback (most recent call last):
  File "/mnt/d/user1/Unicy_Cons_Fitlong_hard04/NeuralPolish/brnn/ctc_polish.py", line 29, in <module>
    model = Model(config.Depth, config.Vocab_size, config.model.Embed_size,
  File "/home/user/miniconda3/envs/neuralpolish/lib/python3.9/site-packages/torch/nn/modules/module.py", line 852, in to
    return self._apply(convert)
  File "/home/user/miniconda3/envs/neuralpolish/lib/python3.9/site-packages/torch/nn/modules/module.py", line 530, in _apply
    module._apply(fn)
  File "/home/user/miniconda3/envs/neuralpolish/lib/python3.9/site-packages/torch/nn/modules/module.py", line 552, in _apply
    param_applied = fn(param)
  File "/home/user/miniconda3/envs/neuralpolish/lib/python3.9/site-packages/torch/nn/modules/module.py", line 850, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/user/miniconda3/envs/neuralpolish/lib/python3.9/site-packages/torch/cuda/__init__.py", line 166, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

---------- Deleting files ---------------

**Comment by huangnengCSU** [comment]
To Ayixon:
    I also met the problem before. I ran the program again and it worked. The problem seems to come from a python call to a shell command to execute `samtools mpileup`, but the code and shell command are fine. You can try to run the error command separately. I think it will not report error. Then try to run the project again.
```
samtools mpileup -B --reference /mnt/d/user1/Unicy_Cons_Fitlong_hard04/NeuralPolish/test04/assembly_racon.fasta -r 1:660001-670000 --output-QNAME /mnt/d/user1/Unicy_Cons_Fitlong_hard04/NeuralPolish/test04/filter_aln.sort.bam -q 0 -Q 13 -o /mnt/d/user1/Unicy_Cons_Fitlong_hard04/NeuralPolish/test04/pileups/1:660001-670000.mpileup
```

Best,
Neng
